site_name: Walkabout
site_description: 'User Manual for Walkabout 1.0'
site_author: 'Daniel Livingston (EES-16, LANL)'

repo_name: 'lanl/walkabout'
repo_url: 'https://github.com/lanl/walkabout'

copyright: 'Copyright &copy; 2019 Triad National Security, LLC'

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'deep orange'
  logo:
    icon: 'directions_walk'

nav:
  - Home: index.md
  - User Guide:
    - Introduction: user-guide/1-introduction.md
    - Technical Basis: user-guide/2-technical-basis.md
    - Overview of Input: user-guide/3-overview-of-input.md
    - Verification Tests: user-guide/4-verification-tests.md
    - Acceptance Tests: user-guide/5-acceptance-tests.md
    - Known Issues: user-guide/6-known-issues.md
    - Conclusions: user-guide/7-conclusions.md
    - References: user-guide/references.md
    - Appendix A Files: user-guide/appendix-A.md
    - Appendix A.1 Control: user-guide/appendix-A1.md
    - Appendix A.2 Geometry: user-guide/appendix-A2.md
    - Appendix A.3 Model: user-guide/appendix-A3.md
    - Appendix A.4 Output: user-guide/appendix-A4.md
  - About:
    - Release Notes: about/release-notes.md
    - Acknowledgements: about/acknowledgements.md
    - License: about/license.md

site_dir: html/

use_directory_urls: false

markdown_extensions:
  - mdx_math

extra_javascript: 
  - mathjax-config.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
